### ISSUE TITLE
UI freezes when toggling between tabs/pages

### ISSUE THREAD

**Issue by jinangs** [nuagenetworks/visualization-framework#460]
VSS UI freezes stating dashboard is loading configuration file. I see this while toggling between different pages.

```

main.769b328e.js:54  prev state ObjectES: pe {size: 1, _root: de, __ownerID: undefined, __hash: undefined, __altered: false}VSD: pe {size: 3, _root: de, __ownerID: undefined, __hash: undefined, __altered: false}configurations: pe {size: 3, _root: de, __ownerID: undefined, __hash: undefined, __altered: false}interface: pe {size: 7, _root: de, __ownerID: undefined, __hash: undefined, __altered: false}messageBox: pe {size: 4, _root: de, __ownerID: undefined, __hash: undefined, __altered: false}router: {routes: Array(2), params: {…}, location: {…}, components: Array(2)}services: pe {size: 1, _root: de, __ownerID: undefined, __hash: undefined, __altered: false}__proto__: Object
main.769b328e.js:54  action ObjectconfigType: "visualizations"data: {id: "vss-domain-traffic-top-dpg", graph: "BarGraph", title: "Top Destination Policy Groups by Count", description: "This barchart represents top 5 destination policy …y total no of packets registered in a given time.", author: "Ronak Shah", …}id: "vss-domain-traffic-top-dpg"type: "CONFIG_DID_RECEIVE_RESPONSE"__proto__: Object
main.769b328e.js:54  error Error: No service named undefined has been registered yet!
    at u (main.769b328e.js:8)
    at Object.c [as getRequestID] (main.769b328e.js:8)
    at s.K [as finalMapStateToProps] (main.769b328e.js:27)
    at s.computeStateProps (main.769b328e.js:46)
    at s.updateStatePropsIfNeeded (main.769b328e.js:46)
    at s.render (main.769b328e.js:46)
    at p._renderValidatedComponentWithoutOwnerOrContext (main.769b328e.js:52)
    at p._renderValidatedComponent (main.769b328e.js:52)
    at p._updateRenderedComponent (main.769b328e.js:52)
    at p._performComponentUpdate (main.769b328e.js:52)
main.769b328e.js:54  next state Object
main.769b328e.js:54  action @ 15:05:41.333 CONFIG_DID_RECEIVE_ERROR
main.769b328e.js:54  prev state ObjectES: pe {size: 1, _root: de, __ownerID: undefined, __hash: undefined, __altered: false}VSD: pe {size: 3, _root: de, __ownerID: undefined, __hash: undefined, __altered: false}configurations: pe {size: 3, _root: de, __ownerID: undefined, __hash: undefined, __altered: false}interface: pe {size: 7, _root: de, __ownerID: undefined, __hash: undefined, __altered: false}messageBox: pe {size: 4, _root: de, __ownerID: undefined, __hash: undefined, __altered: false}router: {routes: Array(2), params: {…}, location: {…}, components: Array(2)}services: pe {size: 1, _root: de, __ownerID: undefined, __hash: undefined, __altered: false}__proto__: Object
main.769b328e.js:54  action ObjectconfigType: "visualizations"error: "No service named undefined has been registered yet!"id: "vss-domain-traffic-top-dpg"type: "CONFIG_DID_RECEIVE_ERROR"__proto__: Object
main.769b328e.js:54  error Error: No service named undefined has been registered yet!
    at u (main.769b328e.js:8)
    at Object.c [as getRequestID] (main.769b328e.js:8)
    at s.K [as finalMapStateToProps] (main.769b328e.js:27)
    at s.computeStateProps (main.769b328e.js:46)
    at s.updateStatePropsIfNeeded (main.769b328e.js:46)
    at s.render (main.769b328e.js:46)
    at p._renderValidatedComponentWithoutOwnerOrContext (main.769b328e.js:52)
    at p._renderValidatedComponent (main.769b328e.js:52)
    at p._updateRenderedComponent (main.769b328e.js:52)
    at p._performComponentUpdate (main.769b328e.js:52)
```
![vssuifreeze](https://user-images.githubusercontent.com/17169726/29642368-41f4d63c-881d-11e7-8c57-123cb90509a5.jpg)

**Comment by nxanil** [comment]
@jinangs 

I am not able to reproduce it. 

Do you have more details like which branch you are working upon? 
and what will be the URL for the same? 
Are you able re-generate it, if so please share a video or steps?

Also, I will keep this error in mind and in future if it pops up, then I wil

**Comment by jinangs** [comment]
@nxanil I was working on master (0.0) and hit this when I toggled between different domains in an enterprise. However, I don't see this with the latest build. Will get you a setup if I see it again.
